feat: s3 업로드 기능 구현
interview-partner/interview-partner pull request #30
Opened 2024-05-15 15:38 UTC by zs0057

## Overview
- s3 업로드 기능 구현 했습니다.
- DB에 있는 file_path는 S3에 저장된 pdf 파일의 경로입니다.
- DB에 있는 translated_file_path는 S3에 저장된 txt 파일의 경로입니다.

## Change Log
- gradle 변경
- S3 Config 생성
- Resume 변경
- ResumeUploadService 변경
- S3UploadService 생성

## To Reviewer
- Resume 생성자를 통해 DB에 잘 저장되는지 봐주세요
- 저장되는 것들이 정확하나 확인해주세요

## Issue Tags
- Closed: #29

2024-05-15 16:04 UTC, junest66 requested changes
코드리뷰 했습니다. 확인해주시고 수정 해주세요! 혹시 s3 저장된 화면 스크린샷 같이 올려주실수 있나요?!

2024-05-18 01:25 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/ResumeUploadService.java
> +        String bucketName = "interviewpartnerbucket"; // 미리 생성된 버킷 이름
1. bucketname yml에 저장해서 보안처리 완료했습니다.
2. 매개변수 간소화를 위해 S3UploadService에서 private final로 선언했습니다.

좋은 의견 감사합니다!

2024-05-18 03:56 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/ResumeUploadService.java
> +            // 예외 메시지를 로깅
피드백 감사합니다.

2024-05-18 03:56 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/ResumeUploadService.java
> +        resumeRepository.save(new Resume(member.get(), originalName, storedFileName, pdfFileKey, txtFileKey));
많이 배워갑니다

2024-05-18 03:56 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/S3UploadService.java
> +            throw new IllegalArgumentException("Only PDF files are allowed.");
넵

2024-05-18 05:17 UTC, junest66 approved these changes

2024-05-18 05:18 UTC, merged