feat: AI 인터뷰 생성
interview-partner/interview-partner pull request #66
Opened 2024-05-25 16:36 UTC by zs0057

## Overview
- AI 인터뷰 생성 API 개발 했습니다.
- gpt api 3.5 turbo 모델 사용했습니다.
- model_answer의 값은 "tmp"를 넣었습니다.
- s3 다운로드 기능 서비스함수 구현했습니다.
- 정규표현식 이용하여 gpt api한테 받은 값을 파싱했습니다.
- Interview 엔티티에 interview_type 추가했습니다.

## Change Log
- init.sql 수정
- build.gradle 수정
- ErrorCode 수정
- InterviewController 생성
- AiInterviewRequest 생성
- Interview 수정
- AiInterviewCreateService 생성
- MakingQuestionService 생성
- S3DownloadService 생성

## To Reviewer
- AiInterviewRequest, InterviewController 에서 스웨거 사용이 적절히 이뤄졌나 봐주세요
- 예외처리가 잘 이뤄졌는지 봐주세요
- secretKey들이 적절하게 보안이 됐는지 봐주세요

## Issue Tags
- Closed: #39

2024-05-25 19:58 UTC, junest66 requested changes
코드 작성하시느라 고생하셨습니다!! 수정 요청사항 확인부탁드립니다!

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/dto/AiInterviewRequest.java
> +    private Long resume_id;
이력서 ID, 멤버 ID 변수를 카멜케이스 형식으로 바꿔주세요!
resume_id -> resumeId
member_id -> memberId

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
> +    private final S3DownloadService s3DownloadService;
해당 코드는 현재 파일에서 사용안하는것 같은데 사용안하시면 삭제하셔야 할 것 같아요!

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
> +        Long Interview_id = aiInterviewCreateService.create(customUserDetails.getMemberId(), aiInterviewRequest);
변수를 카멜케이스형식으로 고쳐주세요!

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/service/AiInterviewCreateService.java
> +        String resume_txt = s3DownloadService.getFileContent(resume.getTranslatedFilePath());
여기도 카멜케이스으로 변환해야합니다

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/service/MakingQuestionService.java
> +public class MakingQuestionService {
해당 파일에서 사용한 변수 카멜케이스형식 변환해야합니다

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/service/MakingQuestionService.java
> +
불필요한 개행이 있습니다.

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/service/MakingQuestionService.java
> +
불필요한 개행이 있습니다.

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/service/MakingQuestionService.java
> +public class MakingQuestionService {
또한 클래스이름을 MakingQuestionService 보다 QuestionMakingService 이건 어떨까요?
질문생성서비스가 더 의미가 명확하고 가독성이 좋을 것으로 생각합니다!

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/dto/AiInterviewRequest.java
> +public class AiInterviewRequest {
유효성검사를 추가해야하지않을까요? 최대 질문 갯수라든지?, 이력서는 필수, 뭐.. 공백이면 안되는 필드도 있을 것 같아요!
컨트롤러에서 `@RequestBody`에  부분에 `@Valid` 선언해서 `jakarta.validation.constraints` 에 있는 유효성 검사 함수를 해당 클래스에서 사용하시면 됩니다!

2024-05-25 19:58 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
> +                    @ApiResponse(responseCode = "400", description = "S3 객체 읽기 오류", content = @Content),
spring doc 에서는 코드당 하나의 응답만을 작성 가능해서 현재 400이 두개 작성돼 있는데, 하나로 통합하셔야합니다. 또한 GPT 질문 생성시에도 에러 부분도 추가하시면 좋겠습니다!

2024-05-26 01:04 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/dto/AiInterviewRequest.java
> +    private Long resume_id;
넵!

2024-05-26 01:04 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
> +    private final S3DownloadService s3DownloadService;
넵!

2024-05-26 01:07 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
> +        Long Interview_id = aiInterviewCreateService.create(customUserDetails.getMemberId(), aiInterviewRequest);
넵!

2024-05-26 01:07 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/AiInterviewCreateService.java
> +        String resume_txt = s3DownloadService.getFileContent(resume.getTranslatedFilePath());
넵!

2024-05-26 01:08 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/MakingQuestionService.java
> +public class MakingQuestionService {
좋은 의견입니다!
수정하겠습니다!

2024-05-26 01:10 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/MakingQuestionService.java
> +
감사합니다!

2024-05-26 01:11 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/MakingQuestionService.java
> +
처리했습니다 감사합니다!

2024-05-26 11:15 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/dto/AiInterviewRequest.java
> +public class AiInterviewRequest {
넵 감사합니다!

2024-05-26 11:22 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
> +                    @ApiResponse(responseCode = "400", description = "S3 객체 읽기 오류", content = @Content),
질문 생성시 에러 코드도 400이라 
 @ApiResponse(responseCode = "400", description = "요청 형식에 맞지 않음", content = @Content),
 이런식으로 작성하겠습니다!

2024-05-27 05:47 UTC, junest66 approved these changes
확인하였습니다!

2024-05-27 05:51 UTC, merged