feat: 답변 저장 API 작성
interview-partner/interview-partner pull request #91
Opened 2024-05-31 16:15 UTC by zs0057

## Overview
- 답변 저장 기능 구현했습니다.
- questionId와 AnswerSaveRequest가 주어지면 이를 UserAnswer로 변경하여 user_answer 테이블에 저장합니다.

## Change Log
- ErrorCode 수정
- InterviewController 수정 (이름변경)
- QuestionController 추가
- UserAnswer 수정
- AnswerSaveRequest 추가
- AnswerSaveService 추가
- InterviewService 추가
- InterviewCreateService 수정 (이름변경)
- QuestionCreateService 수정 (이름변경)
- QuestionLookupService 수정 (이름변경)

## To Reviewer
- 인터뷰 소유자 확인하는 기능 계속 쓰여서 InterviewService 따로 만들어 구현했습니다.
- user_answer 이름 아직은 변경안하는 것이 좋을 것 같습니다.
- AnswerSaveRequest에서 toEntity 구현 했습니다.
- 클래스 이름 Finder -> Lookup 으로 변경, Making -> Create로 변경하였습니다.

## Issue Tags
- Closed: #87

2024-05-31 17:41 UTC, junest66 requested changes
해당 변경요청사항 확인해주세요!

2024-05-31 23:58 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/AnswerSaveService.java
> +
넵 수정하겠습니다

2024-06-01 00:07 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/repository/InterviewRepository.java
> +    Interview findByQuestionsId(Long questionId);
일단 코드는 잘 동작합니다! 아마 quetsion과 interview 관계가 N : 1이여서 문제없이 작동하는 것으로 보입니다.

QuestionRepository에 작성하라고 하신 말씀은 questionId로 Question 객체를 찾고 그 Question 객체로 Interview 객체를 찾아서 Interview에 있는 소유자와 현재 사용자를 비교하는 플로우로 작성하란 말씀인가요?

2024-06-01 01:11 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/repository/InterviewRepository.java
> +    Interview findByQuestionsId(Long questionId);
수정한 것은 다음과 같습니다.

QuestionRepository에 있는 findInterviewByQuestionId 메서드를 이용하여 Interview 객체를 받고 해당 객체의 멤버의 아이디와 현재 사용자의 ID를 비교하는 식으로 만들었습니다.

또한 기존방식은 validateInterviewOwnership를 사용해서 InterviewId를 매개변수로 받아 InterviewRepository에서 또 Member를 찾으러 DB에 접근하는 방법이였는데,

해당 메서드를 오버로딩하여 파라미터로 Interview 객체를 받아 DB에 접근하지 않고 바로 해당 Interview의 MemberId를 받는식으로 코드를 구성했습니다.

좋은 피드백 감사합니다!

2024-06-01 03:04 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/service/QuestionLookupService.java
> +    private final InterviewService InterviewService;
변수명 interviewService 로 수정해주세요!

2024-06-01 03:07 UTC, junest66 requested changes
코드리뷰했습니다!

2024-06-01 03:07 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/service/QuestionLookupService.java
> +    private final InterviewService InterviewService;
변수명 수정 부탁드립니다

2024-06-01 03:09 UTC, junest66 commented on server/src/main/java/com/vip/interviewpartner/repository/InterviewRepository.java
> +    Interview findByQuestionsId(Long questionId);
네 알겠습니다!

2024-06-01 03:32 UTC, zs0057 commented on server/src/main/java/com/vip/interviewpartner/service/QuestionLookupService.java
> +    private final InterviewService InterviewService;
수정 완료했습니다.

찾아보니 안쓰는 import 문도 있어서 추가적으로 제거했습니다.

찾아주셔서 감사합니다!

2024-06-01 03:37 UTC, junest66 approved these changes
확인했습니다!

2024-06-01 03:37 UTC, merged